language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.0
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=4.0.*
        - php: 7.1
          env: SYMFONY_VERSION=4.1.*
        - php: 7.1
          env: SYMFONY_VERSION=4.2.*
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
          env: SYMFONY_VERSION=3.4.*
        - php: 7.2
          env: SYMFONY_VERSION=4.0.*
        - php: 7.2
          env: SYMFONY_VERSION=4.1.*
        - php: 7.2
          env: SYMFONY_VERSION=4.2.*
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.3
          env: SYMFONY_VERSION=3.4.*
        - php: 7.3
          env: SYMFONY_VERSION=4.0.*
        - php: 7.3
          env: SYMFONY_VERSION=4.1.*
        - php: 7.3
          env: SYMFONY_VERSION=4.2.*
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.4
          env: SYMFONY_VERSION=3.4.*
        - php: 7.4
          env: SYMFONY_VERSION=4.0.*
        - php: 7.4
          env: SYMFONY_VERSION=4.1.*
        - php: 7.4
          env: SYMFONY_VERSION=4.2.*
    allow_failures:
        - php: 7.4

before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
